### ISSUE TITLE
invalid URL with 1 unread chapter (novel.next)

### ISSUE THREAD

**Issue by SaltatorMortis** [Spark-NF/firefox-novel-updates#2] opened 2019-02-20 00:30 UTC
Any Novels with exact one Release will always link to:
`moz-extension://addon-UUID/src/popup/undefined`
im using Firefox 65.0.1(64 Bit).
with the if another Chapter is released the Next link is fixed automaticly.

only the novel.next has a Undefined url,
novel.latest still has still a valid URL

**Comment by Spark-NF** [comment] 2019-02-20 16:43
I could see in the code how this could happen (`url: !url.includes("novelupdates.com/extnu/") ? url : undefined`), however I can't reproduce after testing on a bunch of novels with a single chapter, such as "15 cm Between You and Me".

Do you have an example of such broken novel?

**Comment by SaltatorMortis** [comment] 2019-02-20 18:03
sorry my fault, 
I mean not novels with 1 chapter, i mean 1 unread chapter (Next).


atleast on my end i rarly get a url with `novelupdates.com/extnu` from my readinglist(i dont know why but they link direct to the website)
the `novelupdates.com/extnu` links i get only from the Novelpage

**Comment by Spark-NF** [comment] 2019-02-21 15:50
Oh indeed, the link seems broken as long as the next chapter and the latest chapter are the same. I just pushed a fix, I'll make a new release when I advanced a little bit more on issue #1. 👍

**Closed as completed by Spark-NF** 2019-02-21 15:50 UTC
Labels: bug
